name: Gradle Check

on: [push]

jobs:
  check:
    name: gradle check w/ Java 11

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle wrapper integrity check
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('versions.lock') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew check

      - name: Archive distribution artifacts
        uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: |
            distribution/build/distZip/*.zip
